MODEL:
  TYPE: swin
  NAME: swin_patch2_window4_32_cifar-10
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 48
    DEPTHS: [ 2,  6, 2 ]
    NUM_HEADS: [ 3, 6, 12]
    WINDOW_SIZE: 4
    PATCH_SIZE: 2
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
DATA:
  IMG_SIZE: 32
  DATASET: 'cifar-10'